services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Rcdesign\Rcdesign\:
    resource: "../Classes/*"

  Rcdesign\Rcdesign\DataProcessing\SanitizeIdProcessor:
    public: true

  Extcode\Cart\EventListener\Order\Create\OrderNumber:
    arguments:
      $persistenceManager: '@TYPO3\CMS\Extbase\Persistence\Generic\PersistenceManager'
      $options:
        prefix: "IFBB-"
        suffix: "-SHOP"
        offset: 10000
        format: "%09d"
    tags:
      - name: event.listener
        identifier: "cart--order--create--order-number"
        event: Extcode\Cart\Event\Order\NumberGeneratorEvent
        after: "cart--order--create--order"
