base: "https://shop.at/"
baseVariants:
  - base: "https://shop.ddev.site/"
    condition: 'applicationContext == "Development/DDEV"'
errorHandling:
  - errorCode: 404
    errorHandler: Page
    errorContentSource: "t3://page?uid=7"
languages:
  - title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_DE.utf8
    navigationTitle: Deutsch
    flag: at
    hreflang: de-DE
    websiteTitle: ""
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: .html
    index: index
    map:
      .html: 0
      feed.xml: 9818
      calendar.ical: 9819
      sitemap.xml: 1533906435
routes:
  - route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3_src/\r\nDisallow: /template/\r\nAllow: /typo3/sysext/frontend/Resources/Public/*\r\nAllow: /template/Resources/Public/*\r\nSitemap: https://shop.at/sitemap.xml?sitemap=pages\r\nSitemap: https://shop.at/sitemap.xml?sitemap=news"
websiteTitle: ""
